#!/bin/sh

DECMAC=`../mac2dec $@`
snmpwalk -v2c -c public -On 192.168.1.9 1.3.6.1.4.1.9.9.599.1.3.1.1.8.$DECMAC \
 | sed -e 's/ \([^ ][^ ]\) \([^ ][^ ]\) \([^ ][^ ]\) \([^ ][^ ]\) \([^ ][^ ]\) \([^ ][^ ]\)/ \1:\2:\3:\4:\5:\6/g' \
 | sed -f waptable.sed

./rssi.sh $@

exit

 | while read F1 F2 STUFF
   do
     echo $F1 `../dec2hex $F2` $STUFF
   done
